#!/bin/bash

command_exists () {
  type "$1" &> /dev/null;
}

# Globals come from filez and are intentionally consumed here.
# SOURCES
# these provide a list of files based on $root_file
# they should return 1 if they cannot provide results
# print results and return 0 if they can

zoxide_source () {
  command_exists zoxide || return 1

  zoxide query --list
}

git_source () {
  command_exists git || return 1

  # check that we are in a git repo
  # root_file is set by filez before this helper is sourced.
  # shellcheck disable=SC2154
  git -C "$root_file" rev-parse --is-inside-work-tree &> /dev/null || return 1

  git -C "$root_file" ls-files
}

fd_source () {
  command_exists fd || return 1

  declare -a args=(--type f)
  # hidden is set by filez before this helper is sourced.
  # shellcheck disable=SC2154
  [[ $hidden = true ]] && args+=(--hidden)
  # color is set by filez before this helper is sourced.
  # shellcheck disable=SC2154
  [[ $color = true ]] && args+=(--color always)

  fd "${args[@]}" . "$root_file"
}

find_source () {
  command_exists find || return 1

  declare -a args=(-type f -prune)
  [[ $hidden = true ]] || args+=(-not -path "*/\.*")

  find "$root_file" "${args[@]}"
}

rg_source () {
  command_exists rg || return 1

  declare -a args=(--files)
  # hidden is set by filez before this helper is sourced.
  # shellcheck disable=SC2154
  [[ $hidden = true ]] && args+=(--hidden)
  # color is set by filez before this helper is sourced.
  # shellcheck disable=SC2154
  [[ $color = true ]] && args+=(--color always)

  rg "${args[@]}" "$root_file"
}


# FUNCTIONS

sources=(
  git_source
  rg_source
  zoxide_source
  fd_source
  find_source
)

# terminal colors
red=$(tput setaf 1)
grn=$(tput setaf 2)
rst=$(tput sgr0)

fzf_src () {
  for source in "${sources[@]}"; do
    # run function
    if "$source"; then
      # debug is set by filez before this helper is sourced.
      # shellcheck disable=SC2154
      if [[ $debug = true ]]; then # debug print, success case
        echo -e "\n${grn}source: $source  r: $root_file  c: $color  h: $hidden${rst}"
      fi

      return 0
    fi
  done

  # debug is set by filez before this helper is sourced.
  # shellcheck disable=SC2154
  if [[ $debug = true ]]; then # debug print, failure case
    echo -e "\n${red}r: $root_file  c: $color  h: $hidden${rst}"
  fi
  return 1
}
