# C-a bindings
# suggested use is to source this in outer of nested tmux->ssh->tmux
set-environment -g PREFIX "C-a"

unbind-key -q C-b
unbind-key -q C-Space
unbind-key -q C-a
unbind-key -q b
unbind-key -q Space
unbind-key -q a

set -g prefix C-a
set -g prefix2 None

# send prefix to nested tmux
bind-key a send-prefix

# switch prefix
bind-key Space source-file ~/.config/tmux/prefix_space.tmux.conf \; display-message "Prefix changed to C-Space"
bind-key b source-file ~/.config/tmux/prefix_b.tmux.conf \; display-message "Prefix changed to C-b"
