# C-Space bindings
# suggested use is to source this in inner of nested tmux->ssh->tmux

unbind-key -q C-b
unbind-key -q C-Space
unbind-key -q C-a
unbind-key -q b
unbind-key -q Space
unbind-key -q a

set -g prefix C-Space
set -g prefix2 None

# send prefix to nested tmux
bind-key Space send-prefix

# switch prefix
bind-key a source-file ~/.config/tmux/prefix_a.tmux.conf \; display-message "Prefix changed to C-a"
bind-key b source-file ~/.config/tmux/prefix_b.tmux.conf \; display-message "Prefix changed to C-b"
