shell = "zsh"

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

# -- deferred loading support ------------------------------------------------

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
rev = "53a26e287fbbe2dcebb3aa1801546c6de32416fa"
apply = ["source"]

# -- theme -------------------------------------------------------------------

[plugins.minimal-theme]
local = "~/.config/zsh/themes"
use = ["minimal.zsh-theme"]

# -- plugins (immediate) -----------------------------------------------------

# -- plugins (deferred) ------------------------------------------------------

[plugins.forgit]
github = "wfxr/forgit"
rev = "d4bece432b8c4d2be631abf1e2e76b49f5c87f26"
apply = ["defer"]

[plugins.fzf]
local = "~/.config/zsh/plugins"
use = ["fzf.zsh"]
apply = ["defer"]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
rev = "3d574ccf48804b10dca52625df13da5edae7f553"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
rev = "85919cd1ffa7d2d5412f6d3fe437ebdbeeec4fc5"
apply = ["defer"]
