nnoremap <leader>Dn ]c|" d(iff) n(ext)
nnoremap <leader>Dp [c|" d(iff) p(revious)
nnoremap <leader>Dg :diffget |" d(iff) g(et)
nnoremap <leader>Do :diffget other<cr>|" d(iff) (get) o(ther)
nnoremap <leader>Db :diffget base<cr>|" d(iff) (get) b(ase)
nnoremap <leader>Du :diffput|" d(iff) (p)u(t)
